CREATE TABLE IF NOT EXISTS security_exceptions (
    id                  INT AUTO_INCREMENT PRIMARY KEY,
    questionario_id     INT NOT NULL,
    source              ENUM('pir','manuale') NOT NULL DEFAULT 'pir',
    requisito_tipo      ENUM('catalogo','default_design','specifico','manuale') NOT NULL DEFAULT 'manuale',
    requisito_ref_id    INT NULL,
    pir_review_id       INT NULL,
    codice              VARCHAR(120),
    titolo              VARCHAR(500) NOT NULL,
    categoria           VARCHAR(250),
    motivo              TEXT,
    data_rientro        DATE NULL,
    approvato_da        VARCHAR(300),
    stato               ENUM('aperta','rientrata','annullata') NOT NULL DEFAULT 'aperta',
    note                TEXT,
    created_by_user_id  INT NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (questionario_id) REFERENCES questionari(id) ON DELETE CASCADE,
    FOREIGN KEY (pir_review_id) REFERENCES pir_requirement_reviews(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by_user_id) REFERENCES utenti(id) ON DELETE SET NULL,
    UNIQUE KEY uq_security_exception_pir (questionario_id, requisito_tipo, requisito_ref_id),
    KEY idx_security_exceptions_due (data_rientro, stato),
    KEY idx_security_exceptions_project (questionario_id, stato)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
