-- Seed: Domande
INSERT INTO domande (codice, categoria, testo, tipo, ordine) VALUES
  ('nuova_realizzazione','Tipologia di progetto','Il progetto e una nuova realizzazione?','bool',10),
  ('modifica','Tipologia di progetto','Il progetto e una modifica/aggiornamento di un servizio esistente?','bool',20),
  ('nuovi_infrastrutturali','Caratteristiche','Il progetto prevede di introdurre nuovi elementi infrastrutturali?','bool',30),
  ('fornitori_critici','Caratteristiche','Il progetto coinvolge fornitori critici che impattano sull erogazione del servizio?','bool',40),
  ('dati_pers_clienti','Dati trattati','Il progetto tratta dati personali comuni dei clienti?','bool',50),
  ('dati_part_clienti','Dati trattati','Il progetto tratta dati particolari (sensibili) dei clienti?','bool',60),
  ('dati_pers_dipendenti','Dati trattati','Il progetto tratta dati personali comuni dei dipendenti?','bool',70),
  ('dati_part_dipendenti','Dati trattati','Il progetto tratta dati particolari (sensibili) dei dipendenti?','bool',80),
  ('dati_pers_fornitori','Dati trattati','Il progetto tratta dati personali comuni dei fornitori?','bool',90),
  ('dati_aziendali','Dati trattati','Il progetto tratta dati aziendali riservati?','bool',100),
  ('dati_tecnici','Dati trattati','Il progetto tratta dati tecnici o di configurazione?','bool',110),
  ('funz_applicative','Funzionalita','Il progetto introduce funzionalita applicative (SaaS, interfacce utente, logiche di business)?','bool',120),
  ('funz_paas','Funzionalita','Il progetto introduce funzionalita di supporto ad altri servizi (PaaS, middleware)?','bool',130),
  ('funz_iaas','Funzionalita','Il progetto introduce funzionalita di tipo infrastrutturale (IaaS, networking, OS, storage)?','bool',140),
  ('funz_solo_admin','Funzionalita','Il progetto prevede solo funzionalita amministrative di servizi non modificati in altro modo?','bool',150),
  ('usr_pubblico','Utenti del servizio','Il servizio sara accessibile da pubblico anonimo o non identificato?','bool',160),
  ('usr_clienti_priv','Utenti del servizio','Il servizio sara accessibile da clienti privati o individuali?','bool',170),
  ('usr_personale_soc','Utenti del servizio','Il servizio sara accessibile da personale di societa clienti?','bool',180),
  ('usr_personale_pa','Utenti del servizio','Il servizio sara accessibile da personale delle Pubbliche Amministrazioni?','bool',190),
  ('usr_personale_for','Utenti del servizio','Il servizio sara accessibile da personale di societa fornitrici?','bool',200),
  ('usr_interni','Utenti del servizio','Il servizio sara accessibile da utenti interni (dipendenti Azienda e consulenti)?','bool',210),
  ('mercato_enterprise','Mercato','Il servizio e rivolto al mercato enterprise?','bool',220),
  ('mercato_business','Mercato','Il servizio e rivolto al mercato business?','bool',230),
  ('mercato_online','Mercato','Il servizio e rivolto al mercato on-line?','bool',240),
  ('serv_ecs','Tipologia servizio','Il servizio e un servizio gestito (ECS)?','bool',250),
  ('serv_saas','Tipologia servizio','Il servizio e un SaaS - servizio applicativo?','bool',260),
  ('serv_paas','Tipologia servizio','Il servizio e un PaaS - servizio di piattaforma o middleware?','bool',270),
  ('serv_iaas','Tipologia servizio','Il servizio e un IaaS - servizio di infrastruttura?','bool',280),
  ('serv_prodotto','Tipologia servizio','Il servizio e un prodotto (software e/o hardware consegnato al cliente)?','bool',290),
  ('serv_it4it','Tipologia servizio','Il servizio e un servizio IT4IT?','bool',300),
  ('int_web_usr_internet','Interfacce esposte','Interfacce web per utenti esposte su internet?','bool',310),
  ('int_web_usr_privata','Interfacce esposte','Interfacce web per utenti esposte su connettivita privata?','bool',320),
  ('int_web_usr_interna','Interfacce esposte','Interfacce web per utenti esposte su rete interna?','bool',330),
  ('int_web_adm_internet','Interfacce esposte','Interfacce web amministrative esposte su internet?','bool',340),
  ('int_web_adm_privata','Interfacce esposte','Interfacce web amministrative esposte su connettivita privata?','bool',350),
  ('int_web_adm_interna','Interfacce esposte','Interfacce web amministrative esposte su rete interna?','bool',360),
  ('int_cli_usr_internet','Interfacce esposte','Interfacce CLI per utenti esposte su internet?','bool',370),
  ('int_cli_usr_privata','Interfacce esposte','Interfacce CLI per utenti esposte su connettivita privata?','bool',380),
  ('int_cli_usr_interna','Interfacce esposte','Interfacce CLI per utenti esposte su rete interna?','bool',390),
  ('int_cli_adm_internet','Interfacce esposte','Interfacce CLI amministrative esposte su internet?','bool',400),
  ('int_cli_adm_privata','Interfacce esposte','Interfacce CLI amministrative esposte su connettivita privata?','bool',410),
  ('int_cli_adm_interna','Interfacce esposte','Interfacce CLI amministrative esposte su rete interna?','bool',420),
  ('int_api_internet','Interfacce esposte','API esposte su internet?','bool',430),
  ('int_api_privata','Interfacce esposte','API esposte su connettivita privata?','bool',440),
  ('int_api_interna','Interfacce esposte','API esposte su rete interna?','bool',450),
  ('int_app_mobile_int','Interfacce esposte','App mobile ad uso interno?','bool',460),
  ('int_app_mobile_pub','Interfacce esposte','App mobile disponibili pubblicamente?','bool',470),
  ('int_app_desktop_int','Interfacce esposte','Applicazioni desktop ad uso interno?','bool',480),
  ('int_app_desktop_pub','Interfacce esposte','Applicazioni desktop disponibili pubblicamente?','bool',490),
  ('flusso_acquisizione','Flussi di dati','Il progetto prevede acquisizione di dati da sistemi esterni?','bool',500),
  ('flusso_esportazione','Flussi di dati','Il progetto prevede esportazione di dati verso sistemi esterni?','bool',510),
  ('acc_adm_azienda','Profili di accesso','Il servizio prevede il ruolo Amministratori aziendali?','bool',520),
  ('acc_adm_cliente','Profili di accesso','Il servizio prevede il ruolo Amministratori cliente?','bool',530),
  ('acc_privilegiati','Profili di accesso','Il servizio prevede il ruolo Utenti privilegiati?','bool',540),
  ('acc_auditor','Profili di accesso','Il servizio prevede il ruolo Auditor?','bool',550),
  ('acc_utenti_base','Profili di accesso','Il servizio prevede il ruolo Utenti base?','bool',560),
  ('acc_sdo','Profili di accesso','Il servizio prevede utenze di assistenza (es. SDO)?','bool',570),
  ('acc_sdo_imp','Profili di accesso','Il servizio prevede utenze di assistenza con impersonation dell utente?','bool',580),
  ('acc_tecnici','Profili di accesso','Il servizio prevede utenze tecniche o di servizio?','bool',590),
  ('auth_integrazione','Autenticazione','Il servizio si integra con un servizio di autenticazione gia esistente?','bool',600),
  ('auth_nuovo','Autenticazione','Il servizio implementa un nuovo sistema di autenticazione?','bool',610),
  ('auth_locale','Autenticazione','Il servizio include implementazione per gestione locale delle anagrafiche?','bool',620);
